name: Update StrawPoll stats
on:
  schedule:
    - cron: "*/5 * * * *"
  workflow_dispatch:
  push:
    paths:
      - "scripts/fetch_strawpoll.mjs"

jobs:
  update:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - run: node --version
      - name: Fetch stats
        env:
          STRAWPOLL_KEY: ${{ secrets.STRAWPOLL_KEY }}
          POLL_ID_MUJER: 7rnzVbMBanO
          POLL_ID_HOMBRE: e6Z2A3DXXgN
        run: node scripts/fetch_strawpoll.mjs
      - name: Commit changes
        run: |
          if [ -n "$(git status --porcelain)" ]; then
            git config user.name "github-actions[bot]"
            git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
            git add data/stats.json
            git commit -m "chore: update stats.json"
            git push
          else
            echo "No changes."
          fi
